# Generated by Django 2.1.3 on 2020-07-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'specs'},
        ),
    ]
