# Generated by Django 2.1.3 on 2020-07-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0002_auto_20200708_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={},
        ),
    ]
